### PR TITLE
Refine GooleAnalyticsProvider

### PR DESCRIPTION
**Pull request by sodastsai**
1. Implement `didShowNewPageView:withProperties:` correctly
Previous implmentation doesn't contain this method. But screen view
event of Google Analytics has to be precoessed separately.

2. Refine `custom dimension` and `custom metrics` checking/finalizing

### CODE REVIEW

**Comment by marciomeschini** [comment]
do you have an ETA for this?
thanks in advance

**Comment by orta** [comment]
Oops, good work on the ping, I'd missed this PR. looks cool to me, merging.

**Comment by marciomeschini** [comment]
thank you!!

**Comment by edu-ap** [comment]
Thank you!

**Pull request merged**
