### PR TITLE
[WIP] Add breadcrumb logging to HockeyApp

### PR DESCRIPTION
**Pull request by alloy**
This will log events and `ARLog` to the Apple System Logging facility and use those to then add context to HockeyApp crash reports.

- [x] Document in README
- [ ] Wait till HockeyApp change is released: https://github.com/bitstadium/HockeySDK-iOS/pull/153
- [x] ~~Set minimum HockeyApp version in ARAnalytics pod spec~~

### CODE REVIEW

**Comment by alloy** [comment]
screen shot 2015-05-08 at 20 23 02

**Comment by orta** [comment]
Best to add a responds to selector for `appProcessIdentifier` given that we have no guarantee if which hockey version someone is using with ARAnalytics

**Comment by alloy** [comment]
Oh, I was wanting to specify a minimum required version of HockeySDK. So you prefer the agnostic version that checks for the method existing?

**Comment by orta** [comment]
I'd prefer that, I've had to downgrade hockey's before

**Comment by alloy** [comment]
@orta Did done :+1:

**Comment by orta** [comment]
I'm pleased. This is basically mergable, let's make the README say "in a future versions of Hockey", and I think there's a CHANGELOG on ARAnalytics, let's get it in there.

**Comment by alloy** [comment]
@orta I’ve asked the hockey people if it’s something they’d merge and if they can give an estimate of the version number. Without a version that README entry is not that useful, so let’s give it a day :)

**Comment by orta** [comment]
rockin

**Comment by orta** [comment]
This doesn't do a perform selector, it won't compile if you're not using your fork:

screen shot 2015-05-11 at 14 54 12

**Comment by alloy** [comment]
@orta Doh.

**Comment by alloy** [comment]
https://github.com/bitstadium/HockeySDK-iOS/pull/153

This can be merged :+1:

**Comment by orta** [comment]
Yeah, cool, whoever sees it green can merger.

**Comment by alloy** [comment]
I can’t merge :)

**Comment by orta** [comment]
hah, well, then all the power is mine

**Comment by alloy** [comment]
Oh, I forgot CHANGELOG

**Pull request merged**
