### PR TITLE
Set category when logging timing events in GoogleAnalytics

### PR DESCRIPTION
**Pull request by BenchR267**
This is the wanted change from https://github.com/orta/ARAnalytics/pull/286 and https://github.com/orta/ARAnalytics/pull/287.

### CODE REVIEW

**Comment by orta** [comment]
Yeah, this makes sense to me 👍

**Comment by BenchR267** [comment]
Thanks for your contribution @Goharhovhannisyan, even if the pull request itself didn't work out that well :)

**Comment by Goharhovhannisyan** [comment]
Thank you too. Sorry for the incorrect pull requests, I didn't know the procedure for creating pull request.
Next time will do it in right way ;)

**Comment by orta** [comment]
No worries, time and patience

**Pull request merged**
