### PR TITLE
Increased deployment target for Localytics.

### PR DESCRIPTION
**Pull request by BenchR267**
This is a smaller change to achieve https://github.com/orta/ARAnalytics/pull/282, fixes https://github.com/orta/ARAnalytics/issues/283.
When building with a lower deployment target, the user will get an error.

### CODE REVIEW

**Comment by garnett** [comment]
@BenchR267 that looks good, but does not fix the podspec which caused actual trouble - Intercom

**Comment by BenchR267** [comment]
@garnett I wanted to do both in different pull requests, but it's of course possible to do both in this one. I'll do it in a few hours :)

**Comment by BenchR267** [comment]
Sorry, took a bit longer. I will merge this.

**Comment by garnett** [comment]
@BenchR267 @orta sorry for posting it here, doing it for keeping the context. This actually won't compile. I don't know how framework embedding works in CocoPods and how macro on screenshot does but it looks like it still takes into account main `ARAnalytics` target, which is 7.0

**Comment by BenchR267** [comment]
I'm not getting it. Isn't the prohibiting of compilation the aim to achieve? We wanted to increase the deployment target for the specific subspecs, so that others are not effected.

**Comment by garnett** [comment]
Deployment target of my app is iOS 9. Expected result for me is to include Intercom + Localytics via ARAnalytics and compile it altogether.
However, during compilation Xcode complains that Intercom is compiled with deployment target<8.0, which is obviously not what I expected.

Does it help @BenchR267 ?

**Comment by BenchR267** [comment]
Can you please take a look and say what is the deployment target of the generated Pods-project?

**Comment by garnett** [comment]
@BenchR267 Pods project itself is iOS8. ARAnalytics sublibrary target is 7.0

**Comment by BenchR267** [comment]
I tried this Podfile in an example project (deployment target iOS 9.0) and have no problems..

```platform :ios, '8.0'

target 'TestARAnalytics' do
  use_frameworks!

  pod 'ARAnalytics/Intercom', :git => 'git@github.com:orta/ARAnalytics.git', :commit => '1ee9fe3c6453f9f710a3b33822337cef17d9813e'

end```

Deployment target of ARAnalytics framework target in Pods project is 8.0.

**Comment by garnett** [comment]
That is really strange. However I see the difference which might be important: I'm not using `use_frameworks`, can you please check without this option?

**Comment by BenchR267** [comment]
Ah ok, I see the problem...

**Comment by BenchR267** [comment]
I'll try something :)

**Comment by BenchR267** [comment]
Hm, it's not that trivial. Is it possible to depend the deployment target on the subspecs that are used @orta?

**Comment by orta** [comment]
I'm not sure, @segiddins - any idea?

**Comment by segiddins** [comment]
CocoaPods will build the PBXNativeTarget with the highest deployment target of any of the subspecs

**Comment by orta** [comment]
Thanks, sounds like it should work then

**Comment by BenchR267** [comment]
Yeah, but I can not confirm this. Having the subspec at deployment target 8.0 does not increase the deployment target of the target. (Using static linking, with dynamic frameworks everything works fine)

**Pull request merged**
