### PR TITLE
[DSL] Don’t dispatch blocks if view controller has been deallocated.

### PR DESCRIPTION
**Pull request by alloy**
While I haven’t been able to proof it, nor create a failing test, I’m pretty sure that this issue leads to some of the cases we’re having where blocks that try to grab properties from VCs that really should not be `nil` lead to exceptions because we’re trying to insert `nil` into a `NSDictionary`.

Also did some faffing to get test suite to run on iOS 9 and some cleanup (not sure why there was a copy of the podspec in `Example/`?).

### CODE REVIEW

**Comment by alloy** [comment]
I don’t know why this is failing. Works fine locally and I’ve changed the Xcode project to build with deployment target 9.0

**Comment by orta** [comment]
Will take a look

**Comment by orta** [comment]
Boo - hiss, works fine on my machine too.

**Comment by orta** [comment]
I bet it's the `pod update` in CI, vs `pod install` which we probably did

**Comment by orta** [comment]
OK, cool 👍

**Comment by orta** [comment]
@alloy this is now shipped as 4.0.2

**Comment by alloy** [comment]
Ahhhhhhhhhh, yeah makes total sense. Thanks 🙌

**Pull request merged**
