### PR TITLE
Chained progressive tracking

### PR DESCRIPTION
**Pull request by banaslee**
Using the responder chain to progressively adding properties to an event.
Events can be sent down the chain by calling -trackEvent:withProperties: on any UIResponder subclass.
UIApplication will find these events and send it to ARAnalytics.
Any UIResponder subclass can override that method to add properties for themselves. This allows adding context to an event without having to have it promptly where the event if initially fired.

### CODE REVIEW

**Comment by orta** [comment]
This is a really interesting idea, I could get into this technique.

To get this merged, I'd like to see some test ( there's pretty good coverage already, so it shouldn't prove too difficult to cover your bases ) so no-one ruins the feature in the future and this will probably require a change in the `ARAnalytics.podspec` because we support OS X & iOS, and OS X has no UI* classes.

**Comment by banaslee** [comment]
Uhh, forgot to check the OS X part of the podspec. It's actually probably more interesting for OS X apps but I have no experience on that.

**Comment by aarondaub** [comment]
This is cool. How do you think about walking the responder chain up front, finding the first UIViewController in the responder chain, and getting the tracking dictionary from that then immediately sending the event? If you use this approach you won't have to add a category to UIApplication and you won't walk the chain past the first UIViewController.

**Comment by banaslee** [comment]
@aarondaub you mean detecting the mainWindow rootViewController and stopping there instead of going to the UIWindow or UIApplication? Well, I just thought this would be a more generic way of doing it while still giving more esoteric configurations a chance of having this working.
Still, I think your alternative covers 99% of the usages.

**Comment by aarondaub** [comment]
@banaslee err, not quite. The responder that starts the process would walk it's chain until it finds a view controller, have that give it a dictionary, then send the event from there.

**Comment by banaslee** [comment]
@aarondaub ok, I get it now. Well, in the case where you use view controller containment you may want the container to provide some more context.
I guess it's also possible to shortcut or cancel it anywhere by overriding the method and not calling the same method on super or on the next responder.

**Comment by aarondaub** [comment]
@banaslee the VC could still provide context from it's container, wanna talk after the demos? i think there may be a miscommunication.

**Comment by banaslee** [comment]
@aarondaub ure ;)

**Comment by aarondaub** [comment]
@banaslee re our currently in progress in person discussion: you're right :) do your thing

**Comment by banaslee** [comment]
Passing! Well, I wouldn't consider this ready still. I want to add a setting on ARAnalytics to enable/disable the screen name tracking on the view controller.
I think it should be disabled by default for now.

Also, what do you guys think of having just one category and differ behaviour according to the subclass like:

if ([self isKindOf:[UIViewController class]]) {
   // Do the UIViewController category stuff
}
else if ([self isKindOf:[UIApplication class]]) {
  // Do the UIApplication category stuff
}
else {
  // Just call self.nextResponder here
}

**Comment by orta** [comment]
>  I want to add a setting on ARAnalytics to enable/disable the screen name tracking on the view controller.

I think the `return nil` is enough for this

**Comment by orta** [comment]
> Also, what do you guys think of having just one category and differ behaviour according to the subclass

I think this makes the code terser and probably easier to override in your custom classes. Makes sense to me.

**Comment by banaslee** [comment]
> > Also, what do you guys think of having just one category and differ behaviour according to the subclass

> I think this makes the code terser and probably easier to override in your custom classes. Makes sense to me.

Well, I just tried and couldn't call super on the view controller part. The way it is actually allows for better encapsulation. I'm just going to make it more solid with one more include on the view controller category.

**Comment by orta** [comment]
OK, sorry, I just moved the example folder from `Bootstrap` to `Example` which broke this PR. From my side this looks good to merge once this is in.

**Comment by banaslee** [comment]
I want to force me to include tests for this before merging.
Will tell you when ready.

**Comment by orta** [comment]
:+1:

**Comment by orta** [comment]
poke

**Comment by orta** [comment]
poke ;)

**Comment by orta** [comment]
Alright, closing.

**Pull request closed without merging**
