### PR TITLE
Code improvements

### PR DESCRIPTION
**Pull request by BenchR267**
Fixes the following issues/bugs:
- https://github.com/orta/ARAnalytics/issues/275
- https://github.com/orta/ARAnalytics/issues/265
- Leanplum SDK was not started

### CODE REVIEW

**Comment by BenchR267** [comment]
Wow, danger is awesome!! :)

**Comment by orta** [comment]
Great - looks good 👍

**Comment by orta** [comment]
Yeah, Danger's awesome

**Comment by BenchR267** [comment]
Unfortunately danger only works for Github.. Would love to use a tool like this with Stash/Bitbucket..

**Comment by BenchR267** [comment]
https://github.com/danger/danger/pull/481 \o/

**Comment by orta** [comment]
:D

**Pull request merged**
