### PR TITLE
Use Google/Analytics instead of deprecated GoogleAnalytics

### PR DESCRIPTION
**Pull request by pietbrauer**
Seems to be a dropin replacement.

### CODE REVIEW

**Comment by orta** [comment]
Ace :+1:

**Comment by orta** [comment]
Deployed as 3.7.0

**Comment by fotiDim** [comment]
'GoogleAnalytics-iOS-SDK' is supposed to be deprecated, not 'GoogleAnalytics'

**Comment by pietbrauer** [comment]
@fotiDim Whats the purpose of your comment? I see you fixed it already in https://github.com/orta/ARAnalytics/pull/244. Both pods are Google provided the only difference is that `GoogleAnalytics` [downloads v3.14.0](https://github.com/CocoaPods/Specs/blob/master/Specs/GoogleAnalytics/3.14.0/GoogleAnalytics.podspec.json#L33) of the SDK and `Google/Analytics` [downloads v3.12.0](https://github.com/CocoaPods/Specs/blob/master/Specs/Google/1.3.2/Google.podspec.json#L92) of the SDK. Both seem to just use `GoogleAnalytics` in the end. A `pod update GoogleAnalytics` has the same effect using the on both pods as `Google/Analytics` does not care which minor version is used.

**Comment by fotiDim** [comment]
It just stumbled upon your PR and since my PR seemed to be reversing yours I wanted to clear out confusion. I haven't read anywhere that pod 'GoogleAnalytics' is deprecated. Also there is a reason to continue using that instead of pod 'Google/Analytics' in order to have bitcode support, as stated here: https://code.google.com/p/analytics-issues/issues/detail?id=671#c122. This is because the top level Google pod doesn't support bitcode.

**Pull request merged**
