### PR TITLE
Adobe provider via ADBMobile

### PR DESCRIPTION
**Pull request by synthemesc**
This is a bit of an awkward addition as the way ADBMobile does things is a bit awkward — specifically, there is contextual information you may add into your analytics, but the vast majority of your configuration happens via an ADBMobileConfig.json file that's bundled into your project.

I followed the convention of using "data" to refer to that additional data (e.g, "setupAdobeWithData:" when I think it's more idiomatic to say "setupAdobeWithDictionary:"), because that's what the ADBMobile documentation refers to and it might confuse others.

This has been used in another project for a few months now and seems to work well.

### CODE REVIEW

**Comment by orta** [comment]
This looks good, any chance you can add yourself to the changelog?

**Comment by synthemesc** [comment]
Will do.

**Comment by orta** [comment]
Should be the same as the rest of the [CHANGELOG](https://github.com/orta/ARAnalytics/blob/master/CHANGELOG.md) - will need a rebase too, just accepted a change that also edits the podspec #179

**Comment by orta** [comment]
I've manually merged this into master, thanks!

**Pull request closed without merging**
