### PR TITLE
Mixpanel provider improvements

### PR DESCRIPTION
**Pull request by rais38**
Update `MixpanelProvider` with useful methods:

- Register and acces to super properties.
- Clears all stored properties and distinct IDs (user logs out).

### CODE REVIEW

**Comment by orta** [comment]
Looks good, can you add something to the CHANGELOG saying you've added some improvements?

**Comment by rais38** [comment]
Of course, I'll do it. Should I add it in the current version ([`3.8.1`](https://github.com/orta/ARAnalytics/blob/master/CHANGELOG.md#version-381))?

**Comment by orta** [comment]
Nah, new version please sir, lets do 3.8.2

**Comment by rais38** [comment]
Done @orta 👍.

**Comment by orta** [comment]
ace

**Pull request merged**
